alias la="ls -a"
alias cd..='cd ..'
alias edit='vi'
alias egrep='grep -E --color=auto'
alias fgrep='grep -F --color=auto'
alias ggo='git grep --pretty=oneline'
alias glgg='git log --graph --max-count=10'
alias glgga='git log --graph --decorate --all'
alias glo='git log --pretty=oneline'
alias glog='git log --oneline --decorate --color --graph'
alias grep='grep --color=auto'
alias fgrep='grep -F --color=auto'
alias ggo='git grep --pretty=oneline'
alias glgg='git log --graph --max-count=10'
alias glgga='git log --graph --decorate --all'
alias glo='git log --pretty=oneline'
alias glog='git log --oneline --decorate --color --graph'
alias grep='grep --color=auto'
alias fgrep='grep -F --color=auto'
alias ggo='git grep --pretty=oneline'
alias glgg='git log --graph --max-count=10'
alias glgga='git log --graph --decorate --all'
alias glo='git log --pretty=oneline'
alias glog='git log --oneline --decorate --color --graph'
alias grep='grep --color=auto'
alias sla='sudo ls -a'
alias svi='sudo vi' 
alias which='(alias; declare -f) | /usr/bin/which --tty-only --read-alias --read-functions --show-tilde --show-dot'
alias xzegrep='xzegrep --color=auto'
alias xzfgrep='xzfgrep --color=auto'
alias xzgrep='xzgrep --color=auto'
alias zegrep='zegrep --color=auto'
alias zfgrep='zfgrep --color=auto'
alias zgrep='zgrep --color=auto'
alias gab='git bz apply --abort'
alias evs='eval "$(ssh-agent -s)"'
alias sha='ssh-add shared/gitssh_id'
