UPDATE systempreferences SET value="3" WHERE variable = 'minPasswordLength';
UPDATE systempreferences SET value="" WHERE variable = 'RequireStrongPassword';
UPDATE systempreferences SET value="1" WHERE variable = 'EnableAdvancedCatalogingEditor';
UPDATE systempreferences SET value="1" WHERE variable = 'ILLModule';
UPDATE systempreferences SET value="1" WHERE variable like '%Log';
UPDATE systempreferences SET value="1" WHERE variable = 'RESTOAuth2ClientCredentials';
UPDATE borrowers SET email="lisette@bywatersolutions.com", branchcode="CPL" WHERE borrowernumber="19";
UPDATE borrowers SET email="lisette@bywatersolutions.com" WHERE borrowernumber="51";
UPDATE borrowers SET branchcode="FPL" WHERE borrowernumber="5";
UPDATE borrowers SET branchcode="FFL" WHERE borrowernumber="45";
UPDATE items SET homebranch="FPL", holdingbranch="FPL" WHERE itemnumber="19";
UPDATE borrower_message_preferences SET borrower_message_preference_id="37", message_attribute_id="4" WHERE borrowernumber="19";
INSERT INTO library_groups (title, ft_local_hold_group) VALUES ('group1', '1');
INSERT INTO library_groups (parent_id, branchcode) VALUES ('1', 'CPL');
INSERT INTO library_groups (parent_id, branchcode) VALUES ('1', 'FFL');
INSERT INTO library_groups (title, ft_local_hold_group) VALUES ('group2', '1');
INSERT INTO library_groups (parent_id, branchcode) VALUES ('4', 'FPL');
INSERT INTO library_groups (parent_id, branchcode) VALUES ('4', 'FRL');
INSERT INTO reserves (borrowernumber, reservedate, biblionumber, branchcode) VALUES ('45', '2025-04-29', '6', 'FFL');
INSERT INTO reserves (borrowernumber, reservedate, biblionumber, branchcode) VALUES ('29', '2025-04-29', '6', 'FRL');
INSERT INTO reserves (borrowernumber, reservedate, biblionumber, branchcode) VALUES ('5', '2025-04-29', '6', 'FPL');
INSERT INTO reserves (borrowernumber, reservedate, biblionumber, branchcode) VALUES ('19', '2025-04-29', '6', 'CPL');
INSERT INTO illrequests (illrequest_id,borrowernumber,biblio_id,branchcode,status,placed,backend) VALUES ('123','16','6','CPL','RequestReceived','2025-04-29','Standard');
UPDATE systempreferences SET value="1" WHERE variable = 'UseTransportCostMatrix';
UPDATE items SET homebranch="MPL", holdingbranch="MPL" WHERE itemnumber="27";
INSERT INTO reserves (borrowernumber, reservedate, biblionumber, branchcode) VALUES ('5', '2025-08-14', '9', 'FPL');
INSERT INTO reserves (borrowernumber, reservedate, biblionumber, branchcode) VALUES ('19', '2025-08-14', '9', 'CPL');
INSERT INTO reserves (borrowernumber, reservedate, biblionumber, branchcode) VALUES ('29', '2025-08-14', '9', 'PVL');
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('CPL', 'FFL', "1.00", "0");
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('CPL', 'MPL', "1.00", "0");
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('FFL', 'CPL', "1.00", "0");
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('FFL', 'MPL', "1.00", "0");
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('FPL', 'CPL', "1.00", "0");
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('FPL', 'MPL', "1.00", "0");
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('MPL', 'FFL', "1.00", "0");
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('MPL', 'CPL', "1.00", "0");
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('MPL', 'PVL', "4.00", "0");
INSERT INTO transport_cost (frombranch, tobranch, cost, disable_transfer) VALUES ('PVL', 'MPL', "4.00", "0");
